import { create } from 'zustand'
import { persist } from 'zustand/middleware'

const translations = {
  ar: {
    chat: 'الدردشة',
    dashboard: 'لوحة التحكم',
    assets: 'الأصول',
    settings: 'الإعدادات',
    newChat: 'دردشة جديدة',
    search: 'البحث',
    deleteChat: 'حذف الدردشة',
    enterPrompt: 'أدخل طلبك هنا...',
    send: 'إرسال',
    generating: 'جاري المعالجة...',
    cost: 'التكلفة',
    totalRuns: 'إجمالي التشغيلات',
    totalAssets: 'إجمالي الأصول',
    costHistory: 'سجل التكاليف',
    providerUsage: 'استخدام المزود',
    recentRuns: 'التشغيلات الأخيرة',
    gallery: 'المعرض',
    filters: 'الفلاتر',
    chatType: 'نوع الدردشة',
    apiStatus: 'حالة API',
    language: 'اللغة',
    theme: 'المظهر',
    english: 'English',
    arabic: 'العربية',
    dark: 'مظلم',
    light: 'فاتح',
    connected: 'متصل',
    disconnected: 'غير متصل',
    deleteAsset: 'حذف الأصل',
    noChats: 'لا توجد دردشات',
    noAssets: 'لا توجد أصول',
    noRuns: 'لا توجد تشغيلات',
    error: 'خطأ',
    success: 'نجح',
    loading: 'جاري التحميل...',
    status: 'الحالة',
    date: 'التاريخ',
    provider: 'المزود',
    cost: 'التكلفة',
    prompt: 'الطلب',
    output: 'الإخراج',
    worldState: 'حالة العالم',
  },
  en: {
    chat: 'Chat',
    dashboard: 'Dashboard',
    assets: 'Assets',
    settings: 'Settings',
    newChat: 'New Chat',
    search: 'Search',
    deleteChat: 'Delete Chat',
    enterPrompt: 'Enter your prompt here...',
    send: 'Send',
    generating: 'Generating...',
    cost: 'Cost',
    totalRuns: 'Total Runs',
    totalAssets: 'Total Assets',
    costHistory: 'Cost History',
    providerUsage: 'Provider Usage',
    recentRuns: 'Recent Runs',
    gallery: 'Gallery',
    filters: 'Filters',
    chatType: 'Chat Type',
    apiStatus: 'API Status',
    language: 'Language',
    theme: 'Theme',
    english: 'English',
    arabic: 'العربية',
    dark: 'Dark',
    light: 'Light',
    connected: 'Connected',
    disconnected: 'Disconnected',
    deleteAsset: 'Delete Asset',
    noChats: 'No chats',
    noAssets: 'No assets',
    noRuns: 'No runs',
    error: 'Error',
    success: 'Success',
    loading: 'Loading...',
    status: 'Status',
    date: 'Date',
    provider: 'Provider',
    cost: 'Cost',
    prompt: 'Prompt',
    output: 'Output',
    worldState: 'World State',
  },
}

export const useUIStore = create(
  persist(
    (set, get) => ({
      language: 'ar',
      theme: 'dark',
      sidebarOpen: true,
      apiConnected: false,

      setLanguage: (language) => set({ language }),
      setTheme: (theme) => set({ theme }),
      setSidebarOpen: (open) => set({ sidebarOpen: open }),
      setApiConnected: (connected) => set({ apiConnected: connected }),

      t: (key) => {
        const { language } = get()
        return translations[language]?.[key] || translations.en[key] || key
      },
    }),
    {
      name: 'wazza-ui-store',
      version: 1,
    }
  )
)
